# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BikePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('frame', 'Frame'), ('fork', 'Fork'), ('damper', 'Damper')], max_length=100)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mount_date', models.DateField()),
                ('last_service_date', models.DateField()),
                ('bike_mounted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='bike.Bike')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
