# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_bikepart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikepart',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikepart',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
