# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20170320_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikepart',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
